/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int PVIRG = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int ATRIB = 9;
  /** RegularExpression Id. */
  int APAREN = 10;
  /** RegularExpression Id. */
  int FPAREN = 11;
  /** RegularExpression Id. */
  int PALRESER = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int ID = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"print\"",
    "<NUM>",
    "<ID>",
  };

}
